name: devffest_ilorin
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^4.5.0
  flutter_svg: ^1.1.5
  provider: ^6.0.3
  get_it: ^7.2.0
  font_awesome_flutter: ^10.2.1
  screenshot: ^1.2.3
  flutter_animate: ^1.0.0
  lottie: ^1.4.3
  file_picker: ^5.2.0+1
  smooth_page_indicator: ^1.0.0+2
  flutter_staggered_grid_view: ^0.6.2
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
